using AppPlatform.Api;
using AppPlatform.Core.Data;
using AppPlatform.Ids;
using AppPlatform.Outbox;
using AppPlatform.Tenancy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppPlatform.Core.Features.Internal;

/// <summary>
/// Creates a tenant, its company, and its first admin invitation.
///
/// This lives in CORE, not platform, for one reason: all of it must commit in a single
/// transaction, and a transaction cannot span two services. Platform holds the commercial
/// record and asks core to do the work.
/// </summary>
public static class ProvisionTenantFeature
{
    public const string ApiKeyHeader = "X-Internal-Key";

    public record ProvisionTenantCommand(string? Name, string? AdminEmail, string? IdempotencyKey);

    public class ProvisionTenantCommandHandler(
        CoreDbContext db,
        IBackgroundTenantScope tenantScope,
        TimeProvider clock)
    {
        public async Task<CommandResult> Handle(
            ProvisionTenantCommand cmd, CancellationToken ct = default)
        {
            var name = cmd.Name?.Trim();
            var email = cmd.AdminEmail?.Trim().ToLowerInvariant();

            if (string.IsNullOrWhiteSpace(name) || string.IsNullOrWhiteSpace(email))
                return CommandResult.Invalid(CoreProblems.ValidationFailed, "Name and admin email are required.");

            var key = cmd.IdempotencyKey?.Trim();
            if (string.IsNullOrWhiteSpace(key))
            {
                return CommandResult.Invalid(
                    CoreProblems.ValidationFailed,
                    "An idempotency key is required so a retried request cannot provision twice.");
            }

            // Checked first as a fast path, but NOT relied on: two concurrent calls both find
            // nothing here. The unique index below is the actual guard.
            if (await db.Tenants.FirstOrDefaultAsync(t => t.ProvisioningKey == key, ct) is { } already)
                return Replay(already, ct);

            var now = clock.GetUtcNow();

            // One transaction around the whole thing. The tenant's key is generated by the
            // database, so its row must be saved before the rows that reference it — and a
            // failure after that point must take the tenant with it, or provisioning leaves a
            // tenant with no company and no way in.
            await using var transaction = await db.Database.BeginTransactionAsync(ct);

            var tenant = new Data.Tenant
            {
                PublicId = PublicId.New("ten").ToString(),
                Name = name,
                Status = TenantLifecycle.Active,
                // Required, not-null, and no database default: omitting it fails the INSERT.
                CreatedAt = now,
                ProvisioningKey = key,
            };

            db.Tenants.Add(tenant);

            try
            {
                await db.SaveChangesAsync(ct);
            }
            catch (Exception ex) when (DatabaseConflict.IsUniqueViolation(ex))
            {
                // A concurrent call won. This is the guard doing its job, not an error: roll
                // back and return the tenant that call created, so both callers see one tenant
                // and the same id. Recording the key AFTER provisioning — which is where this
                // lived before — cannot do this: by then the duplicate already exists.
                await transaction.RollbackAsync(ct);
                db.ChangeTracker.Clear();

                var winner = await db.Tenants.FirstOrDefaultAsync(t => t.ProvisioningKey == key, ct);
                if (winner is not null) return Replay(winner, ct);

                throw;
            }

            // Enter the new tenant so filters and stamping behave exactly as in a request.
            // Nothing below sets TenantId by hand — this is the supported way to write before a
            // session exists, and it is why TenantGuard has no "pre-set TenantId" escape hatch.
            tenantScope.UseTenant(tenant.Id);

            var company = new Company
            {
                PublicId = PublicId.New("co").ToString(),
                Name = name,
            };
            db.Companies.Add(company);
            await db.SaveChangesAsync(ct);

            var admin = new User
            {
                PublicId = PublicId.New("usr").ToString(),
                CompanyId = company.Id,
                Email = email,
                Role = "admin",
                Status = UserStatus.Invited,
            };
            db.Users.Add(admin);

            // The invitation itself. The user_token row stores only a HASH.
            //
            // The plaintext lives in two places until the outbox row is pruned: the delivered
            // email, and this outbox payload. That payload is a password-equivalent credential
            // in a readable table, which is why OutboxWorker prunes delivered messages on the
            // retention schedule rather than leaving them forever.
            var (plaintext, hash) = Services.TokenGenerator.Create();

            db.UserTokens.Add(new UserToken
            {
                UserId = admin.Id,
                Purpose = TokenPurpose.Invite,
                TokenHash = hash,
                CreatedAt = now,
                // Long enough to survive a weekend and a spam folder; short enough that a
                // forgotten invitation is not a permanent way in.
                ExpiresAt = now.AddDays(7),
            });

            // Staged, then committed with everything else. Sending first and committing after
            // is how a recipient ends up holding a link to a tenant that does not exist.
            new Outbox.Outbox(db, clock).AddMessage(
                OutboxTransports.Email,
                destination: email,
                payload: $$"""{"kind":"tenant_admin_invite","userId":"{{admin.PublicId}}","token":"{{plaintext}}"}""");

            await db.SaveChangesAsync(ct);
            await transaction.CommitAsync(ct);

            return CommandResult.Ok(new { tenantId = tenant.PublicId, adminUserId = admin.PublicId });
        }

        /// <summary>
        /// A replay returns the tenant only. The admin user id is deliberately absent: the
        /// invitation was issued on the first call, and re-reading it here would need a tenant
        /// scope this path has not entered.
        /// </summary>
        private static CommandResult Replay(Data.Tenant tenant, CancellationToken ct)
            => CommandResult.Ok(new { tenantId = tenant.PublicId, replayed = true });
    }

    public class Endpoint : IEndpoint
    {
        public void Map(IEndpointRouteBuilder routes) => routes.MapPost(
            "/api/core/v1/internal/tenants",
            async (
                HttpContext http,
                [FromServices] IConfiguration config,
                [FromServices] CoreDbContext db,
                [FromServices] IBackgroundTenantScope tenantScope,
                [FromServices] TimeProvider clock,
                CancellationToken ct) =>
            {
                // Checked BEFORE the body is read, and 404 rather than 401 when unset: an
                // endpoint that answers "unauthorized" announces that it exists. nginx blocks
                // the internal prefix publicly as well; this is the second lock, not the only one.
                var expected = config["Internal:ApiKey"];
                if (string.IsNullOrEmpty(expected)) return Results.NotFound();

                var presented = http.Request.Headers[ApiKeyHeader].FirstOrDefault();
                if (!InternalKey.Matches(expected, presented)) return Results.NotFound();

                var cmd = await http.Request.ReadFromJsonAsync<ProvisionTenantCommand>(ct);
                if (cmd is null)
                    return Results.BadRequest(new { problemCode = CoreProblems.ValidationFailed });

                var handler = new ProvisionTenantCommandHandler(db, tenantScope, clock);
                return (await handler.Handle(cmd, ct)).CreateIResult();
            })
            // No .RequireAuthorization(): there is no session during provisioning. The shared
            // secret is the whole authentication story here, which is why it is checked first
            // and why this path is reviewed as carefully as an anonymous endpoint.
            .AllowAnonymous();
    }
}

public static class InternalKey
{
    /// <summary>
    /// Fixed-time comparison. An ordinary string compare returns as soon as two bytes differ,
    /// which leaks how much of a guessed key was correct — and this key guards tenant creation.
    /// </summary>
    public static bool Matches(string expected, string? presented)
    {
        if (string.IsNullOrEmpty(presented)) return false;

        var a = System.Text.Encoding.UTF8.GetBytes(expected);
        var b = System.Text.Encoding.UTF8.GetBytes(presented);

        return a.Length == b.Length
            && System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(a, b);
    }
}
