// <auto-generated />
using System;
using AppPlatform.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppPlatform.Core.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppPlatform.Core.Data.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("public_id");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_company_tenant_id_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_public_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_company_tenant_id");

                    b.ToTable("company", "core");
                });

            modelBuilder.Entity("AppPlatform.Core.Data.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("public_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_employee");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_employee_tenant_id_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_public_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_tenant_id");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("ix_employee_tenant_id_company_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_tenant_id_email")
                        .HasFilter("email IS NOT NULL AND deleted = false");

                    b.ToTable("employee", "core");
                });

            modelBuilder.Entity("AppPlatform.Core.Data.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expiry");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<bool>("MfaSatisfied")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_satisfied");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_session_tenant_id");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_session_tenant_id_user_id");

                    b.ToTable("session", "identity");
                });

            modelBuilder.Entity("AppPlatform.Core.Data.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IdleTimeoutMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("idle_timeout_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProvisioningKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provisioning_key");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("public_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_public_id");

                    b.ToTable("tenant", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AppPlatform.Core.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("public_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_user_tenant_id_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_public_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_tenant_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_tenant_id_email");

                    b.HasIndex("TenantId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_tenant_id_employee_id")
                        .HasFilter("employee_id IS NOT NULL");

                    b.ToTable("user", "identity");
                });

            modelBuilder.Entity("AppPlatform.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregatePublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("aggregate_public_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_event");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_outbox_event_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_event_tenant_id");

                    b.HasIndex("TenantId", "AggregateType", "AggregatePublicId", "AggregateVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_event_tenant_id_aggregate_type_aggregate_public_id_a");

                    b.ToTable("outbox_event", "core");
                });

            modelBuilder.Entity("AppPlatform.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("destination");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transport");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_message_tenant_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_message_status_next_attempt_at")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("TenantId", "EventId")
                        .HasDatabaseName("ix_outbox_message_tenant_id_event_id");

                    b.ToTable("outbox_message", "core");
                });

            modelBuilder.Entity("AppPlatform.Core.Data.Employee", b =>
                {
                    b.HasOne("AppPlatform.Core.Data.Company", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_company_tenant_id_company_id");
                });

            modelBuilder.Entity("AppPlatform.Core.Data.Session", b =>
                {
                    b.HasOne("AppPlatform.Core.Data.User", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_user_tenant_id_user_id");
                });

            modelBuilder.Entity("AppPlatform.Core.Data.User", b =>
                {
                    b.HasOne("AppPlatform.Core.Data.Employee", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EmployeeId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_employee_tenant_id_employee_id");
                });

            modelBuilder.Entity("AppPlatform.Outbox.OutboxMessage", b =>
                {
                    b.HasOne("AppPlatform.Outbox.OutboxEvent", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EventId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_outbox_message_outbox_event_tenant_id_event_id");
                });
#pragma warning restore 612, 618
        }
    }
}
