START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925185721_AddAuditLog') THEN
    CREATE TABLE core.audit_log (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        actor_kind character varying(20) NOT NULL,
        actor_id uuid,
        actor_name character varying(100),
        action character varying(20) NOT NULL,
        entity_type character varying(100) NOT NULL,
        entity_id character varying(40) NOT NULL,
        changes jsonb NOT NULL,
        CONSTRAINT pk_audit_log PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925185721_AddAuditLog') THEN
    CREATE INDEX ix_audit_log_tenant_id_entity_type_entity_id ON core.audit_log (tenant_id, entity_type, entity_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925185721_AddAuditLog') THEN
    CREATE INDEX ix_audit_log_tenant_id_occurred_at ON core.audit_log (tenant_id, occurred_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925185721_AddAuditLog') THEN
    INSERT INTO core.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925185721_AddAuditLog', '10.0.10');
    END IF;
END $EF$;
COMMIT;

