DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core') THEN
        CREATE SCHEMA core;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS core.__ef_migrations_history (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core') THEN
            CREATE SCHEMA core;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'identity') THEN
            CREATE SCHEMA identity;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE TABLE core.company (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        public_id character varying(34) NOT NULL,
        name character varying(200) NOT NULL,
        legal_name character varying(200),
        active boolean NOT NULL,
        CONSTRAINT pk_company PRIMARY KEY (id),
        CONSTRAINT ak_company_tenant_id_id UNIQUE (tenant_id, id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE TABLE core.outbox_event (
        id uuid NOT NULL,
        tenant_id integer NOT NULL,
        aggregate_type character varying(50) NOT NULL,
        aggregate_public_id character varying(40) NOT NULL,
        aggregate_version bigint NOT NULL,
        event_type character varying(100) NOT NULL,
        payload jsonb NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_outbox_event PRIMARY KEY (id),
        CONSTRAINT ak_outbox_event_tenant_id_id UNIQUE (tenant_id, id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE TABLE core.employee (
        id uuid NOT NULL,
        tenant_id integer NOT NULL,
        company_id integer NOT NULL,
        public_id character varying(34) NOT NULL,
        first_name character varying(100) NOT NULL,
        last_name character varying(100) NOT NULL,
        email character varying(320),
        status character varying(20) NOT NULL,
        version bigint NOT NULL,
        deleted boolean NOT NULL,
        CONSTRAINT pk_employee PRIMARY KEY (id),
        CONSTRAINT ak_employee_tenant_id_id UNIQUE (tenant_id, id),
        CONSTRAINT fk_employee_company_tenant_id_company_id FOREIGN KEY (tenant_id, company_id) REFERENCES core.company (tenant_id, id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE TABLE core.outbox_message (
        id uuid NOT NULL,
        tenant_id integer NOT NULL,
        event_id uuid,
        transport character varying(20) NOT NULL,
        destination character varying(320) NOT NULL,
        payload jsonb NOT NULL,
        status character varying(20) NOT NULL,
        attempts integer NOT NULL,
        next_attempt_at timestamp with time zone NOT NULL,
        locked_until timestamp with time zone,
        completed_at timestamp with time zone,
        last_error character varying(1000),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_outbox_message PRIMARY KEY (id),
        CONSTRAINT fk_outbox_message_outbox_event_tenant_id_event_id FOREIGN KEY (tenant_id, event_id) REFERENCES core.outbox_event (tenant_id, id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE TABLE identity."user" (
        id uuid NOT NULL,
        tenant_id integer NOT NULL,
        company_id integer NOT NULL,
        public_id character varying(34) NOT NULL,
        email character varying(320) NOT NULL,
        role character varying(50) NOT NULL,
        status character varying(20) NOT NULL,
        employee_id uuid,
        CONSTRAINT pk_user PRIMARY KEY (id),
        CONSTRAINT fk_user_employee_tenant_id_employee_id FOREIGN KEY (tenant_id, employee_id) REFERENCES core.employee (tenant_id, id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE UNIQUE INDEX ix_company_public_id ON core.company (public_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE INDEX ix_company_tenant_id ON core.company (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE UNIQUE INDEX ix_employee_public_id ON core.employee (public_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE INDEX ix_employee_tenant_id ON core.employee (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE INDEX ix_employee_tenant_id_company_id ON core.employee (tenant_id, company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE UNIQUE INDEX ix_employee_tenant_id_email ON core.employee (tenant_id, email) WHERE email IS NOT NULL AND deleted = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE INDEX ix_outbox_event_tenant_id ON core.outbox_event (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE UNIQUE INDEX ix_outbox_event_tenant_id_aggregate_type_aggregate_public_id_a ON core.outbox_event (tenant_id, aggregate_type, aggregate_public_id, aggregate_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE INDEX ix_outbox_message_status_next_attempt_at ON core.outbox_message (status, next_attempt_at) WHERE status = 'Pending';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE INDEX ix_outbox_message_tenant_id ON core.outbox_message (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE INDEX ix_outbox_message_tenant_id_event_id ON core.outbox_message (tenant_id, event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE UNIQUE INDEX ix_user_public_id ON identity."user" (public_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE INDEX ix_user_tenant_id ON identity."user" (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE UNIQUE INDEX ix_user_tenant_id_email ON identity."user" (tenant_id, email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    CREATE UNIQUE INDEX ix_user_tenant_id_employee_id ON identity."user" (tenant_id, employee_id) WHERE employee_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004002_InitialCore') THEN
    INSERT INTO core.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925004002_InitialCore', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004032_AddCoreV1Views') THEN
    CREATE SCHEMA IF NOT EXISTS core_v1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004032_AddCoreV1Views') THEN
    CREATE OR REPLACE VIEW core_v1.employee AS
    SELECT id, tenant_id, company_id, public_id,
           first_name, last_name,
           (first_name || ' ' || last_name) AS display_name,
           status
    FROM core.employee
    WHERE deleted = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004032_AddCoreV1Views') THEN
    CREATE OR REPLACE VIEW core_v1.company AS
    SELECT id, tenant_id, public_id, name, active
    FROM core.company;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004032_AddCoreV1Views') THEN
    GRANT USAGE ON SCHEMA core_v1 TO ap_core_rt;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004032_AddCoreV1Views') THEN
    GRANT SELECT ON core_v1.employee, core_v1.company TO ap_core_rt;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925004032_AddCoreV1Views') THEN
    INSERT INTO core.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925004032_AddCoreV1Views', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    ALTER TABLE identity."user" ADD CONSTRAINT ak_user_tenant_id_id UNIQUE (tenant_id, id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    CREATE TABLE identity.session (
        id uuid NOT NULL,
        tenant_id integer NOT NULL,
        user_id uuid NOT NULL,
        mfa_satisfied boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        last_seen_at timestamp with time zone NOT NULL,
        absolute_expiry timestamp with time zone NOT NULL,
        revoked_at timestamp with time zone,
        CONSTRAINT pk_session PRIMARY KEY (id),
        CONSTRAINT fk_session_user_tenant_id_user_id FOREIGN KEY (tenant_id, user_id) REFERENCES identity."user" (tenant_id, id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    CREATE INDEX ix_session_tenant_id ON identity.session (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    CREATE INDEX ix_session_tenant_id_user_id ON identity.session (tenant_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    CREATE SCHEMA IF NOT EXISTS identity_v1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    CREATE OR REPLACE FUNCTION identity_v1.session_context(p_session_id uuid)
    RETURNS TABLE (
      session_id uuid, user_id uuid, tenant_id int, company_id int, tenant_status text,
      role text, user_active boolean, mfa_satisfied boolean, last_seen_at timestamptz,
      absolute_expiry timestamptz, revoked_at timestamptz, employee_id uuid,
      licensed_apps text[], idle_timeout_minutes int)
    LANGUAGE sql
    STABLE
    SECURITY DEFINER
    SET search_path = pg_catalog, pg_temp
    AS $fn$
      SELECT s.id, u.id, u.tenant_id, u.company_id, t.status,
             u.role, (u.status = 'Active'), s.mfa_satisfied, s.last_seen_at,
             s.absolute_expiry, s.revoked_at, u.employee_id,
             coalesce(array_agg(ta.app) FILTER (WHERE ta.app IS NOT NULL), '{}'),
             t.idle_timeout_minutes
      FROM identity.session s
      JOIN identity."user" u ON u.id = s.user_id AND u.tenant_id = s.tenant_id
      JOIN platform.tenant t ON t.id = u.tenant_id
      LEFT JOIN platform.tenant_app ta
        ON ta.tenant_id = u.tenant_id AND ta.revoked_at IS NULL
      WHERE s.id = p_session_id
      GROUP BY s.id, u.id, u.tenant_id, u.company_id, t.status, u.role, u.status,
               s.mfa_satisfied, s.last_seen_at, s.absolute_expiry, s.revoked_at,
               u.employee_id, t.idle_timeout_minutes;
    $fn$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    CREATE OR REPLACE FUNCTION identity_v1.touch_session(p_session_id uuid)
    RETURNS void
    LANGUAGE sql
    SECURITY DEFINER
    SET search_path = pg_catalog, pg_temp
    AS $fn$
      UPDATE identity.session SET last_seen_at = now() WHERE id = p_session_id;
    $fn$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    REVOKE EXECUTE ON FUNCTION identity_v1.session_context(uuid) FROM PUBLIC;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    REVOKE EXECUTE ON FUNCTION identity_v1.touch_session(uuid) FROM PUBLIC;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    GRANT USAGE ON SCHEMA identity_v1 TO ap_core_rt;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    GRANT EXECUTE ON FUNCTION identity_v1.session_context(uuid) TO ap_core_rt;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    GRANT EXECUTE ON FUNCTION identity_v1.touch_session(uuid) TO ap_core_rt;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925034241_AddSessionsAndIdentityV1') THEN
    INSERT INTO core.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925034241_AddSessionsAndIdentityV1', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925045109_AddUserPasswordsAndTokens') THEN
    ALTER TABLE identity."user" ADD password_hash character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925045109_AddUserPasswordsAndTokens') THEN
    CREATE TABLE identity.user_token (
        id uuid NOT NULL,
        tenant_id integer NOT NULL,
        user_id uuid NOT NULL,
        purpose character varying(20) NOT NULL,
        token_hash character varying(64) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        used_at timestamp with time zone,
        CONSTRAINT pk_user_token PRIMARY KEY (id),
        CONSTRAINT fk_user_token_user_tenant_id_user_id FOREIGN KEY (tenant_id, user_id) REFERENCES identity."user" (tenant_id, id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925045109_AddUserPasswordsAndTokens') THEN
    CREATE INDEX ix_user_token_tenant_id ON identity.user_token (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925045109_AddUserPasswordsAndTokens') THEN
    CREATE INDEX ix_user_token_tenant_id_user_id ON identity.user_token (tenant_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925045109_AddUserPasswordsAndTokens') THEN
    CREATE UNIQUE INDEX ix_user_token_token_hash ON identity.user_token (token_hash);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core.__ef_migrations_history WHERE "migration_id" = '20260925045109_AddUserPasswordsAndTokens') THEN
    INSERT INTO core.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925045109_AddUserPasswordsAndTokens', '10.0.10');
    END IF;
END $EF$;
COMMIT;

