START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203443_AddErrorFeed') THEN
    CREATE TABLE platform.error_occurrence (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        reference character varying(40) NOT NULL,
        fingerprint character varying(16) NOT NULL,
        app character varying(20) NOT NULL,
        tenant_id integer,
        count integer NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_error_occurrence PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203443_AddErrorFeed') THEN
    CREATE INDEX ix_error_occurrence_occurred_at ON platform.error_occurrence (occurred_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203443_AddErrorFeed') THEN
    CREATE UNIQUE INDEX ix_error_occurrence_reference ON platform.error_occurrence (reference);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203443_AddErrorFeed') THEN
    CREATE INDEX ix_error_occurrence_tenant_id ON platform.error_occurrence (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203443_AddErrorFeed') THEN
    INSERT INTO platform.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260929203443_AddErrorFeed', '10.0.10');
    END IF;
END $EF$;
COMMIT;

