DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'platform') THEN
        CREATE SCHEMA platform;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS platform.__ef_migrations_history (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'platform') THEN
            CREATE SCHEMA platform;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.audit_log (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        platform_user_id uuid,
        action character varying(100) NOT NULL,
        tenant_public_id character varying(40),
        detail character varying(1000),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_audit_log PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.idempotency_record (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        key character varying(200) NOT NULL,
        operation character varying(100) NOT NULL,
        response_json jsonb NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_idempotency_record PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.platform_user (
        id uuid NOT NULL,
        public_id character varying(34) NOT NULL,
        email character varying(320) NOT NULL,
        password_hash character varying(200) NOT NULL,
        active boolean NOT NULL,
        totp_secret text,
        totp_secret_version integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_platform_user PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.tenant (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        public_id character varying(34) NOT NULL,
        name character varying(200) NOT NULL,
        status character varying(20) NOT NULL,
        idle_timeout_minutes integer,
        created_at timestamp with time zone NOT NULL,
        status_changed_at timestamp with time zone,
        CONSTRAINT pk_tenant PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.platform_session (
        id uuid NOT NULL,
        platform_user_id uuid NOT NULL,
        created_at timestamp with time zone NOT NULL,
        last_seen_at timestamp with time zone NOT NULL,
        absolute_expiry timestamp with time zone NOT NULL,
        revoked_at timestamp with time zone,
        CONSTRAINT pk_platform_session PRIMARY KEY (id),
        CONSTRAINT fk_platform_session_platform_user_platform_user_id FOREIGN KEY (platform_user_id) REFERENCES platform.platform_user (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.tenant_app (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        app character varying(50) NOT NULL,
        granted_at timestamp with time zone NOT NULL,
        revoked_at timestamp with time zone,
        CONSTRAINT pk_tenant_app PRIMARY KEY (id),
        CONSTRAINT fk_tenant_app_tenant_tenant_id FOREIGN KEY (tenant_id) REFERENCES platform.tenant (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE INDEX ix_audit_log_created_at ON platform.audit_log (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE UNIQUE INDEX ix_idempotency_record_operation_key ON platform.idempotency_record (operation, key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE INDEX ix_platform_session_platform_user_id ON platform.platform_session (platform_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE UNIQUE INDEX ix_platform_user_email ON platform.platform_user (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE UNIQUE INDEX ix_platform_user_public_id ON platform.platform_user (public_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE UNIQUE INDEX ix_tenant_public_id ON platform.tenant (public_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE UNIQUE INDEX ix_tenant_app_tenant_id_app ON platform.tenant_app (tenant_id, app) WHERE revoked_at IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    INSERT INTO platform.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925005837_InitialPlatform', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925011803_AddSessionMfaSatisfied') THEN
    ALTER TABLE platform.platform_session ADD mfa_satisfied boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925011803_AddSessionMfaSatisfied') THEN
    INSERT INTO platform.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925011803_AddSessionMfaSatisfied', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925015103_AddTenantProvisioningKey') THEN
    ALTER TABLE platform.tenant ADD provisioning_key character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925015103_AddTenantProvisioningKey') THEN
    CREATE UNIQUE INDEX ix_tenant_provisioning_key ON platform.tenant (provisioning_key) WHERE provisioning_key IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925015103_AddTenantProvisioningKey') THEN
    INSERT INTO platform.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925015103_AddTenantProvisioningKey', '10.0.10');
    END IF;
END $EF$;
COMMIT;

