DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'platform') THEN
        CREATE SCHEMA platform;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS platform.__ef_migrations_history (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'platform') THEN
            CREATE SCHEMA platform;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.audit_log (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        platform_user_id uuid,
        action character varying(100) NOT NULL,
        tenant_public_id character varying(40),
        detail character varying(1000),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_audit_log PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.idempotency_record (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        key character varying(200) NOT NULL,
        operation character varying(100) NOT NULL,
        response_json jsonb NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_idempotency_record PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.platform_user (
        id uuid NOT NULL,
        public_id character varying(34) NOT NULL,
        email character varying(320) NOT NULL,
        password_hash character varying(200) NOT NULL,
        active boolean NOT NULL,
        totp_secret text,
        totp_secret_version integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_platform_user PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.tenant (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        public_id character varying(34) NOT NULL,
        name character varying(200) NOT NULL,
        status character varying(20) NOT NULL,
        idle_timeout_minutes integer,
        created_at timestamp with time zone NOT NULL,
        status_changed_at timestamp with time zone,
        CONSTRAINT pk_tenant PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.platform_session (
        id uuid NOT NULL,
        platform_user_id uuid NOT NULL,
        created_at timestamp with time zone NOT NULL,
        last_seen_at timestamp with time zone NOT NULL,
        absolute_expiry timestamp with time zone NOT NULL,
        revoked_at timestamp with time zone,
        CONSTRAINT pk_platform_session PRIMARY KEY (id),
        CONSTRAINT fk_platform_session_platform_user_platform_user_id FOREIGN KEY (platform_user_id) REFERENCES platform.platform_user (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE TABLE platform.tenant_app (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        app character varying(50) NOT NULL,
        granted_at timestamp with time zone NOT NULL,
        revoked_at timestamp with time zone,
        CONSTRAINT pk_tenant_app PRIMARY KEY (id),
        CONSTRAINT fk_tenant_app_tenant_tenant_id FOREIGN KEY (tenant_id) REFERENCES platform.tenant (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE INDEX ix_audit_log_created_at ON platform.audit_log (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE UNIQUE INDEX ix_idempotency_record_operation_key ON platform.idempotency_record (operation, key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE INDEX ix_platform_session_platform_user_id ON platform.platform_session (platform_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE UNIQUE INDEX ix_platform_user_email ON platform.platform_user (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE UNIQUE INDEX ix_platform_user_public_id ON platform.platform_user (public_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE UNIQUE INDEX ix_tenant_public_id ON platform.tenant (public_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    CREATE UNIQUE INDEX ix_tenant_app_tenant_id_app ON platform.tenant_app (tenant_id, app) WHERE revoked_at IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925005837_InitialPlatform') THEN
    INSERT INTO platform.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925005837_InitialPlatform', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925011803_AddSessionMfaSatisfied') THEN
    ALTER TABLE platform.platform_session ADD mfa_satisfied boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925011803_AddSessionMfaSatisfied') THEN
    INSERT INTO platform.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925011803_AddSessionMfaSatisfied', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925015103_AddTenantProvisioningKey') THEN
    ALTER TABLE platform.tenant ADD provisioning_key character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925015103_AddTenantProvisioningKey') THEN
    CREATE UNIQUE INDEX ix_tenant_provisioning_key ON platform.tenant (provisioning_key) WHERE provisioning_key IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260925015103_AddTenantProvisioningKey') THEN
    INSERT INTO platform.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925015103_AddTenantProvisioningKey', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929182954_AddDataKeysAndOperatorTotp') THEN
    ALTER TABLE platform.platform_user RENAME COLUMN totp_secret TO totp_secret_encrypted;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929182954_AddDataKeysAndOperatorTotp') THEN
    ALTER TABLE platform.platform_user ADD totp_last_used_step bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929182954_AddDataKeysAndOperatorTotp') THEN
    UPDATE platform.platform_session SET revoked_at = now() WHERE revoked_at IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929182954_AddDataKeysAndOperatorTotp') THEN
    CREATE TABLE platform.data_key (
        id uuid NOT NULL,
        kek_fingerprint character varying(16) NOT NULL,
        wrapped_key bytea NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_data_key PRIMARY KEY (id, kek_fingerprint)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929182954_AddDataKeysAndOperatorTotp') THEN
    INSERT INTO platform.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260929182954_AddDataKeysAndOperatorTotp', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203443_AddErrorFeed') THEN
    CREATE TABLE platform.error_occurrence (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        reference character varying(40) NOT NULL,
        fingerprint character varying(16) NOT NULL,
        app character varying(20) NOT NULL,
        tenant_id integer,
        count integer NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_error_occurrence PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203443_AddErrorFeed') THEN
    CREATE INDEX ix_error_occurrence_occurred_at ON platform.error_occurrence (occurred_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203443_AddErrorFeed') THEN
    CREATE UNIQUE INDEX ix_error_occurrence_reference ON platform.error_occurrence (reference);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203443_AddErrorFeed') THEN
    CREATE INDEX ix_error_occurrence_tenant_id ON platform.error_occurrence (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203443_AddErrorFeed') THEN
    INSERT INTO platform.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260929203443_AddErrorFeed', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203446_AddErrorFeedPublishedFunction') THEN
    CREATE SCHEMA IF NOT EXISTS platform_v1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203446_AddErrorFeedPublishedFunction') THEN
    CREATE OR REPLACE FUNCTION platform_v1.record_error(
      p_reference text, p_fingerprint text, p_app text, p_tenant_id int, p_count int,
      p_occurred_at timestamptz)
    RETURNS void
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = pg_catalog, pg_temp
    AS $fn$
    BEGIN
      -- Every column allowlisted by shape. Anything else is refused rather than stored:
      -- this table is metadata only, and free text is where customer data would get in.
      IF p_reference IS NULL OR p_reference !~ '^err_[0-9a-z]{25}$'
         OR p_fingerprint IS NULL OR p_fingerprint !~ '^[0-9a-f]{16}$'
         OR p_app IS NULL OR p_app !~ '^[a-z][a-z0-9_]{1,19}$'
         OR p_count IS NULL OR p_count NOT BETWEEN 1 AND 100000
         OR p_occurred_at IS NULL
         OR p_occurred_at NOT BETWEEN now() - interval '1 day' AND now() + interval '5 minutes'
      THEN
        RAISE EXCEPTION 'platform_v1.record_error refused a malformed occurrence'
          USING ERRCODE = 'invalid_parameter_value';
      END IF;

      INSERT INTO platform.error_occurrence (reference, fingerprint, app, tenant_id, count, occurred_at)
      VALUES (p_reference, p_fingerprint, p_app, p_tenant_id, p_count, p_occurred_at);
    END
    $fn$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203446_AddErrorFeedPublishedFunction') THEN
    REVOKE EXECUTE ON FUNCTION platform_v1.record_error(text, text, text, int, int, timestamptz) FROM PUBLIC;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203446_AddErrorFeedPublishedFunction') THEN
    GRANT USAGE ON SCHEMA platform_v1 TO ap_platform_rt, ap_core_rt, ap_tickets_rt, ap_ledger_rt;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203446_AddErrorFeedPublishedFunction') THEN
    GRANT EXECUTE ON FUNCTION platform_v1.record_error(text, text, text, int, int, timestamptz) TO ap_platform_rt, ap_core_rt, ap_tickets_rt, ap_ledger_rt;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM platform.__ef_migrations_history WHERE "migration_id" = '20260929203446_AddErrorFeedPublishedFunction') THEN
    INSERT INTO platform.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260929203446_AddErrorFeedPublishedFunction', '10.0.10');
    END IF;
END $EF$;
COMMIT;

