DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'ledger') THEN
        CREATE SCHEMA ledger;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS ledger.__ef_migrations_history (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'ledger') THEN
            CREATE SCHEMA ledger;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE TABLE ledger.account (
        id uuid NOT NULL,
        tenant_id integer NOT NULL,
        company_id integer NOT NULL,
        public_id character varying(34) NOT NULL,
        code character varying(20) NOT NULL,
        name character varying(200) NOT NULL,
        type character varying(20) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_account PRIMARY KEY (id),
        CONSTRAINT ak_account_tenant_id_company_id_id UNIQUE (tenant_id, company_id, id),
        CONSTRAINT ck_account_code CHECK (code ~ '^[0-9A-Za-z][0-9A-Za-z.-]{0,19}$')
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE TABLE ledger.audit_log (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        actor_kind character varying(20) NOT NULL,
        actor_id uuid,
        actor_name character varying(100),
        action character varying(20) NOT NULL,
        entity_type character varying(100) NOT NULL,
        entity_id character varying(40) NOT NULL,
        changes jsonb NOT NULL,
        CONSTRAINT pk_audit_log PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE TABLE ledger.entry_sequence (
        tenant_id integer NOT NULL,
        company_id integer NOT NULL,
        fiscal_year integer NOT NULL,
        last_number integer NOT NULL,
        CONSTRAINT pk_entry_sequence PRIMARY KEY (tenant_id, company_id, fiscal_year)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE TABLE ledger.journal_entry (
        id uuid NOT NULL,
        tenant_id integer NOT NULL,
        company_id integer NOT NULL,
        public_id character varying(34) NOT NULL,
        number integer NOT NULL,
        fiscal_year integer NOT NULL,
        entry_date date NOT NULL,
        memo character varying(500) NOT NULL,
        currency character(3) NOT NULL,
        posted_at timestamp with time zone NOT NULL,
        reverses_entry_id uuid,
        idempotency_key character varying(100),
        request_fingerprint character varying(64),
        line_count integer NOT NULL,
        CONSTRAINT pk_journal_entry PRIMARY KEY (id),
        CONSTRAINT ak_journal_entry_tenant_id_company_id_id UNIQUE (tenant_id, company_id, id),
        CONSTRAINT ck_journal_entry_currency CHECK (currency ~ '^[A-Z]{3}$'),
        CONSTRAINT ck_journal_entry_fiscal_year CHECK (fiscal_year = extract(year from entry_date)),
        CONSTRAINT ck_journal_entry_line_count CHECK (line_count >= 2),
        CONSTRAINT ck_journal_entry_number CHECK (number > 0),
        CONSTRAINT fk_journal_entry_journal_entry_tenant_id_company_id_reverses_e FOREIGN KEY (tenant_id, company_id, reverses_entry_id) REFERENCES ledger.journal_entry (tenant_id, company_id, id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE TABLE ledger.outbox_event (
        id uuid NOT NULL,
        tenant_id integer NOT NULL,
        aggregate_type character varying(50) NOT NULL,
        aggregate_public_id character varying(40) NOT NULL,
        aggregate_version bigint NOT NULL,
        event_type character varying(100) NOT NULL,
        payload jsonb NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_outbox_event PRIMARY KEY (id),
        CONSTRAINT ak_outbox_event_tenant_id_id UNIQUE (tenant_id, id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE TABLE ledger.journal_line (
        id uuid NOT NULL,
        tenant_id integer NOT NULL,
        company_id integer NOT NULL,
        entry_id uuid NOT NULL,
        account_id uuid NOT NULL,
        line_number integer NOT NULL,
        amount_minor bigint NOT NULL,
        memo character varying(500),
        CONSTRAINT pk_journal_line PRIMARY KEY (id),
        CONSTRAINT ck_journal_line_amount_negatable CHECK (amount_minor > -9223372036854775808),
        CONSTRAINT ck_journal_line_amount_nonzero CHECK (amount_minor <> 0),
        CONSTRAINT fk_journal_line_account_tenant_id_company_id_account_id FOREIGN KEY (tenant_id, company_id, account_id) REFERENCES ledger.account (tenant_id, company_id, id) ON DELETE RESTRICT,
        CONSTRAINT fk_journal_line_journal_entry_tenant_id_company_id_entry_id FOREIGN KEY (tenant_id, company_id, entry_id) REFERENCES ledger.journal_entry (tenant_id, company_id, id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE TABLE ledger.outbox_message (
        id uuid NOT NULL,
        tenant_id integer NOT NULL,
        event_id uuid,
        transport character varying(20) NOT NULL,
        destination character varying(320) NOT NULL,
        payload jsonb NOT NULL,
        status character varying(20) NOT NULL,
        attempts integer NOT NULL,
        next_attempt_at timestamp with time zone NOT NULL,
        locked_until timestamp with time zone,
        completed_at timestamp with time zone,
        last_error character varying(1000),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_outbox_message PRIMARY KEY (id),
        CONSTRAINT fk_outbox_message_outbox_event_tenant_id_event_id FOREIGN KEY (tenant_id, event_id) REFERENCES ledger.outbox_event (tenant_id, id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE UNIQUE INDEX ix_account_public_id ON ledger.account (public_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_account_tenant_id ON ledger.account (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE UNIQUE INDEX ix_account_tenant_id_company_id_code ON ledger.account (tenant_id, company_id, code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_audit_log_tenant_id_entity_type_entity_id ON ledger.audit_log (tenant_id, entity_type, entity_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_audit_log_tenant_id_occurred_at ON ledger.audit_log (tenant_id, occurred_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_entry_sequence_tenant_id ON ledger.entry_sequence (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE UNIQUE INDEX ix_journal_entry_public_id ON ledger.journal_entry (public_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_journal_entry_tenant_id ON ledger.journal_entry (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE UNIQUE INDEX ix_journal_entry_tenant_id_company_id_fiscal_year_number ON ledger.journal_entry (tenant_id, company_id, fiscal_year, number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_journal_entry_tenant_id_company_id_reverses_entry_id ON ledger.journal_entry (tenant_id, company_id, reverses_entry_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE UNIQUE INDEX ix_journal_entry_tenant_id_idempotency_key ON ledger.journal_entry (tenant_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE UNIQUE INDEX ix_journal_entry_tenant_id_reverses_entry_id ON ledger.journal_entry (tenant_id, reverses_entry_id) WHERE reverses_entry_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_journal_line_tenant_id ON ledger.journal_line (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_journal_line_tenant_id_account_id ON ledger.journal_line (tenant_id, account_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_journal_line_tenant_id_company_id_account_id ON ledger.journal_line (tenant_id, company_id, account_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_journal_line_tenant_id_company_id_entry_id ON ledger.journal_line (tenant_id, company_id, entry_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE UNIQUE INDEX ix_journal_line_tenant_id_entry_id_line_number ON ledger.journal_line (tenant_id, entry_id, line_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_outbox_event_tenant_id ON ledger.outbox_event (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE UNIQUE INDEX ix_outbox_event_tenant_id_aggregate_type_aggregate_public_id_a ON ledger.outbox_event (tenant_id, aggregate_type, aggregate_public_id, aggregate_version);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_outbox_message_status_next_attempt_at ON ledger.outbox_message (status, next_attempt_at) WHERE status = 'Pending';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_outbox_message_tenant_id ON ledger.outbox_message (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    CREATE INDEX ix_outbox_message_tenant_id_event_id ON ledger.outbox_message (tenant_id, event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ledger.__ef_migrations_history WHERE "migration_id" = '20260925205954_InitialLedger') THEN
    INSERT INTO ledger.__ef_migrations_history (migration_id, product_version)
    VALUES ('20260925205954_InitialLedger', '10.0.10');
    END IF;
END $EF$;
COMMIT;

