// <auto-generated />
using System;
using AppPlatform.Ledger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppPlatform.Ledger.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260925211934_AddPeriodClose")]
    partial class AddPeriodClose
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppPlatform.Audit.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_kind");

                    b.Property<string>("ActorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_name");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_log_tenant_id_occurred_at");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_tenant_id_entity_type_entity_id");

                    b.ToTable("audit_log", "ledger");
                });

            modelBuilder.Entity("AppPlatform.Ledger.Data.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("public_id");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasAlternateKey("TenantId", "CompanyId", "Id")
                        .HasName("ak_account_tenant_id_company_id_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_account_public_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_account_tenant_id");

                    b.HasIndex("TenantId", "CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_account_tenant_id_company_id_code");

                    b.ToTable("account", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_account_code", "code ~ '^[0-9A-Za-z][0-9A-Za-z.-]{0,19}$'");
                        });
                });

            modelBuilder.Entity("AppPlatform.Ledger.Data.Books", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ClosedThrough")
                        .HasColumnType("date")
                        .HasColumnName("closed_through");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("public_id");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasAlternateKey("TenantId", "CompanyId")
                        .HasName("ak_books_tenant_id_company_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_books_public_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_books_tenant_id");

                    b.ToTable("books", "ledger");
                });

            modelBuilder.Entity("AppPlatform.Ledger.Data.EntrySequence", b =>
                {
                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_number");

                    b.HasKey("TenantId", "CompanyId", "FiscalYear")
                        .HasName("pk_entry_sequence");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_entry_sequence_tenant_id");

                    b.ToTable("entry_sequence", "ledger");
                });

            modelBuilder.Entity("AppPlatform.Ledger.Data.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer")
                        .HasColumnName("line_count");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("memo");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("public_id");

                    b.Property<string>("RequestFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_entry_id");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_entry");

                    b.HasAlternateKey("TenantId", "CompanyId", "Id")
                        .HasName("ak_journal_entry_tenant_id_company_id_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entry_public_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_journal_entry_tenant_id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entry_tenant_id_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("TenantId", "ReversesEntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entry_tenant_id_reverses_entry_id")
                        .HasFilter("reverses_entry_id IS NOT NULL");

                    b.HasIndex("TenantId", "CompanyId", "ReversesEntryId")
                        .HasDatabaseName("ix_journal_entry_tenant_id_company_id_reverses_entry_id");

                    b.HasIndex("TenantId", "CompanyId", "FiscalYear", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entry_tenant_id_company_id_fiscal_year_number");

                    b.ToTable("journal_entry", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_journal_entry_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_journal_entry_fiscal_year", "fiscal_year = extract(year from entry_date)");

                            t.HasCheckConstraint("ck_journal_entry_line_count", "line_count >= 2");

                            t.HasCheckConstraint("ck_journal_entry_number", "number > 0");
                        });
                });

            modelBuilder.Entity("AppPlatform.Ledger.Data.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("Memo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("memo");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_line");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_journal_line_tenant_id");

                    b.HasIndex("TenantId", "AccountId")
                        .HasDatabaseName("ix_journal_line_tenant_id_account_id");

                    b.HasIndex("TenantId", "CompanyId", "AccountId")
                        .HasDatabaseName("ix_journal_line_tenant_id_company_id_account_id");

                    b.HasIndex("TenantId", "CompanyId", "EntryId")
                        .HasDatabaseName("ix_journal_line_tenant_id_company_id_entry_id");

                    b.HasIndex("TenantId", "EntryId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_line_tenant_id_entry_id_line_number");

                    b.ToTable("journal_line", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_journal_line_amount_negatable", "amount_minor > -9223372036854775808");

                            t.HasCheckConstraint("ck_journal_line_amount_nonzero", "amount_minor <> 0");
                        });
                });

            modelBuilder.Entity("AppPlatform.Ledger.Data.PublishedCompany", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_id");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable((string)null);

                    b.ToView("company", "core_v1");
                });

            modelBuilder.Entity("AppPlatform.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregatePublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("aggregate_public_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_event");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_outbox_event_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_event_tenant_id");

                    b.HasIndex("TenantId", "AggregateType", "AggregatePublicId", "AggregateVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_event_tenant_id_aggregate_type_aggregate_public_id_a");

                    b.ToTable("outbox_event", "ledger");
                });

            modelBuilder.Entity("AppPlatform.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("destination");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transport");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_message_tenant_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_message_status_next_attempt_at")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("TenantId", "EventId")
                        .HasDatabaseName("ix_outbox_message_tenant_id_event_id");

                    b.ToTable("outbox_message", "ledger");
                });

            modelBuilder.Entity("AppPlatform.Ledger.Data.JournalEntry", b =>
                {
                    b.HasOne("AppPlatform.Ledger.Data.Books", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .HasPrincipalKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entry_books_tenant_id_company_id");

                    b.HasOne("AppPlatform.Ledger.Data.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "ReversesEntryId")
                        .HasPrincipalKey("TenantId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_entry_journal_entry_tenant_id_company_id_reverses_e");
                });

            modelBuilder.Entity("AppPlatform.Ledger.Data.JournalLine", b =>
                {
                    b.HasOne("AppPlatform.Ledger.Data.Account", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "AccountId")
                        .HasPrincipalKey("TenantId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_line_account_tenant_id_company_id_account_id");

                    b.HasOne("AppPlatform.Ledger.Data.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("TenantId", "CompanyId", "EntryId")
                        .HasPrincipalKey("TenantId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_line_journal_entry_tenant_id_company_id_entry_id");
                });

            modelBuilder.Entity("AppPlatform.Outbox.OutboxMessage", b =>
                {
                    b.HasOne("AppPlatform.Outbox.OutboxEvent", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EventId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_outbox_message_outbox_event_tenant_id_event_id");
                });

            modelBuilder.Entity("AppPlatform.Ledger.Data.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
